import type { Basket, Business, Profile, Reservation } from './types'

const now = Date.now()
const hours = (n: number) => new Date(now + n * 3600 * 1000).toISOString()

export const seedBusinesses: Business[] = [
  {
    id: 'biz-1',
    ownerId: 'merchant-demo-1',
    name: 'Boulangerie El Baraka',
    category: 'bakery',
    wilaya: '16',
    commune: 'Bab Ezzouar',
    address: 'Rue des Frères Boukhelifa, Bab Ezzouar, Alger',
    whatsapp: '+213550000001',
    latitude: 36.7181,
    longitude: 3.1875,
  },
  {
    id: 'biz-2',
    ownerId: 'merchant-demo-2',
    name: 'Restaurant Dar Diaf',
    category: 'restaurant',
    wilaya: '31',
    commune: 'Es Senia',
    address: 'Boulevard de la Soummam, Oran',
    whatsapp: '+213550000002',
    latitude: 35.6369,
    longitude: -0.6172,
  },
  {
    id: 'biz-3',
    ownerId: 'merchant-demo-3',
    name: 'Supérette Ain El Fouara',
    category: 'grocery',
    wilaya: '19',
    commune: 'Sétif Centre',
    address: 'Avenue du 8 Mai 1945, Sétif',
    whatsapp: '+213550000003',
    latitude: 36.1898,
    longitude: 5.4108,
  },
  {
    id: 'biz-4',
    ownerId: 'merchant-demo-4',
    name: 'Pâtisserie Amir',
    category: 'bakery',
    wilaya: '25',
    commune: 'Constantine Centre',
    address: 'Rue Larbi Ben M\'hidi, Constantine',
    whatsapp: '+213550000004',
    latitude: 36.365,
    longitude: 6.6147,
  },
]

export const seedBaskets: Basket[] = [
  {
    id: 'bsk-1',
    businessId: 'biz-1',
    title: 'Panier viennoiseries & pain du jour',
    description: 'Assortiment de croissants, pains au chocolat et pain traditionnel invendus du jour.',
    priceOriginal: 800,
    priceDiscounted: 250,
    quantityTotal: 6,
    quantityAvailable: 4,
    pickupStart: hours(2),
    pickupEnd: hours(4),
    status: 'active',
    isIftar: false,
    createdAt: hours(-3),
  },
  {
    id: 'bsk-2',
    businessId: 'biz-1',
    title: "Panier f'tour — pâtisseries orientales",
    description: 'Zlabia, kalb el louz et baklawa préparés du jour, panier spécial iftar.',
    priceOriginal: 1500,
    priceDiscounted: 500,
    quantityTotal: 10,
    quantityAvailable: 7,
    pickupStart: hours(5),
    pickupEnd: hours(6),
    status: 'active',
    isIftar: true,
    createdAt: hours(-2),
  },
  {
    id: 'bsk-3',
    businessId: 'biz-2',
    title: 'Panier surprise plats du jour',
    description: "Restes de plats traiteur du midi : couscous, chorba, plats mijotés, selon arrivage.",
    priceOriginal: 1200,
    priceDiscounted: 400,
    quantityTotal: 5,
    quantityAvailable: 0,
    pickupStart: hours(1),
    pickupEnd: hours(2),
    status: 'sold_out',
    isIftar: false,
    createdAt: hours(-4),
  },
  {
    id: 'bsk-4',
    businessId: 'biz-3',
    title: 'Panier produits proches de la date limite',
    description: 'Yaourts, fromages et produits laitiers à consommer rapidement, encore parfaitement bons.',
    priceOriginal: 900,
    priceDiscounted: 300,
    quantityTotal: 8,
    quantityAvailable: 8,
    pickupStart: hours(3),
    pickupEnd: hours(8),
    status: 'active',
    isIftar: false,
    createdAt: hours(-1),
  },
  {
    id: 'bsk-5',
    businessId: 'biz-4',
    title: "Panier f'tour — corbeille de gâteaux",
    description: 'Sélection de gâteaux traditionnels et modernes invendus, parfaits pour la rupture du jeûne.',
    priceOriginal: 2000,
    priceDiscounted: 700,
    quantityTotal: 4,
    quantityAvailable: 2,
    pickupStart: hours(6),
    pickupEnd: hours(7),
    status: 'active',
    isIftar: true,
    createdAt: hours(-1),
  },
]

export const seedProfiles: Profile[] = [
  { id: 'merchant-demo-1', fullName: 'Karim B.', phone: '+213550000001', role: 'merchant', wilaya: '16' },
  { id: 'merchant-demo-2', fullName: 'Amina S.', phone: '+213550000002', role: 'merchant', wilaya: '31' },
  { id: 'merchant-demo-3', fullName: 'Yacine T.', phone: '+213550000003', role: 'merchant', wilaya: '19' },
  { id: 'merchant-demo-4', fullName: 'Nadia R.', phone: '+213550000004', role: 'merchant', wilaya: '25' },
]

export const seedReservations: Reservation[] = []
